# data

import random

# Combine the front and back card items into a single list
card_issues = [
    "Incorrect Font: The font used does not match official Pokémon card fonts.",
    "Spelling Errors: Misspellings are present on the card.",
    "Incorrect Card Numbering: The card number and set symbol do not match the official card list.",
    "Wrong Holo Pattern: The holographic pattern is incorrect or inconsistent with the set.",
    "Inconsistent Design Details: Design details do not match known genuine cards.",
    "Uneven Borders: The borders are too thick, too thin, or uneven.",
    "Poor Print Quality: The print appears blurry or pixelated.",
    "Wrong Material Indicators: Visual clues suggest the card is made of improper material.",
    "Incorrect Texture Appearance: The texture looks different from known genuine cards.",
    "Lack of Gloss: The card lacks the glossy finish typical of authentic cards.",
    "Incorrect Size Indicators: Elements suggest the card is of incorrect size.",
    "Inappropriate Weight Indicators: The card appears too heavy or too light based on digital examination.",
    "Incorrect Thickness Indicators: Visuals suggest the card has improper thickness.",
    "Inconsistent Colors: Colors are off, either too bright or too dull.",
    "Misaligned Text: Text is not properly aligned.",
    "Wrong Set Symbol: The set symbol is incorrect.",
    "Incorrect Energy Symbols: The energy symbols are incorrect.",
    "Fake Holo Foil Patterns: The holographic foil does not match known patterns.",
    "Non-Reflective Foil: The holo foil does not reflect light correctly.",
    "Incorrect Card Number: The card number does not match the depicted Pokémon.",
    "Duplicate Card Numbers: Multiple cards have the same number but different content.",
    "Wrong Language: The text is in the wrong language for an English card.",
    "Incorrect Evolution Lines: Evolution lines do not match known Pokémon evolutions.",
    "Wrong Illustrator Name: The illustrator name is incorrect.",
    "Incorrect Moves: The moves listed are incorrect or unknown.",
    "Wrong Weakness/Resistance Symbols: The weakness or resistance symbols are incorrect.",
    "Incorrect HP: The HP is incorrect for the depicted Pokémon.",
    "Fake Set Codes: Set codes that do not exist in the official database.",
    "Incorrect Expansion Symbol: The expansion symbol does not match the set.",
    "Fake or Nonexistent Cards: Cards depict Pokémon that do not exist.",
    "Altered Card Art: The card art is different from known official versions.",
    "Fake Promo Symbols: Promo symbols are incorrect or missing.",
    "Wrong Artist Credits: The artist credit is incorrect.",
    "Poor Cutting Indicators: The card edges appear jagged or uneven.",
    "Different Card Appearance: The card does not match the appearance of known genuine cards.",
    "Incorrect Shading: The shading on the card is incorrect.",
    "Fake Watermark Indicators: Incorrect or missing watermarks visible in high-quality images.",
    "Incorrect Year: The year printed on the card is incorrect.",
    "Fake Edition Stamps: The edition stamp is incorrect or missing.",
    "Wrong Evolution Requirements: Evolution requirements are incorrect.",
    "Incorrect Rarity Symbols: The rarity symbol is incorrect or missing.",
    "Incorrect Card Type: The card type (e.g., Basic, Stage 1) is incorrect.",
    "Wrong Weakness: The weakness listed is incorrect.",
    "Wrong Resistance: The resistance listed is incorrect.",
    "Fake Card Abilities: The abilities listed do not exist.",
    "Fake Trainer Cards: Trainer cards have incorrect effects or text.",
    "Incorrect Pokémon Abilities: Pokémon abilities are incorrect.",
    "Wrong Attack Costs: The attack costs are incorrect.",
    "Fake Energy Cards: Energy cards have incorrect symbols or text.",
    "Incorrect Card Layout: The layout does not match official Pokémon card standards.",
    "Incorrect Font: The font used does not match official Pokémon card fonts.",
    "Spelling Errors: Misspellings are present on the card back.",
    "Incorrect Logo: The Pokémon logo is incorrect or poorly replicated.",
    "Inconsistent Colors: Colors are off, either too bright or too dull.",
    "Blurry Print: The print appears blurry or pixelated.",
    "Uneven Borders: The borders are too thick, too thin, or uneven.",
    "Poor Image Quality: The image quality is low or pixelated.",
    "Wrong Blue Color: The blue color on the back is incorrect.",
    "Incorrect Poké Ball Design: The Poké Ball design is incorrect.",
    "Wrong Color Gradient: The gradient of the blue color is off.",
    "Incorrect Pokémon Text Placement: The placement of the 'Pokémon' text is incorrect.",
    "Incorrect Shadowing: The shadowing on the card is incorrect.",
    "Poor Border Quality: The border quality is poor or uneven.",
    "Different Card Back Design: The design does not match known genuine cards.",
    "Incorrect Centering: The centering of the design is off.",
    "Wrong Font Size: The font size is incorrect.",
    "Incorrect Size Indicators: Elements suggest the card is of incorrect size.",
    "Fake Watermark Indicators: Incorrect or missing watermarks visible in high-quality images.",
    "Different Print Quality Indicators: The print quality appears different from genuine cards.",
    "Incorrect Texture Indicators: Visual signs suggest incorrect texture.",
    "Inconsistent Gloss: The gloss on the back is inconsistent with genuine cards.",
    "Different Blue Shade: The shade of blue is different from genuine cards.",
    "Incorrect Poké Ball Proportions: The proportions of the Poké Ball are incorrect.",
    "Wrong Pokémon Logo Placement: The placement of the logo is incorrect.",
    "Incorrect Color Balance: The color balance is off.",
    "Poor Print Alignment: The print alignment is incorrect.",
    "Different Printing Process Indicators: The printing process appears different from genuine cards.",
    "Wrong Card Layer Indicators: Layers visible in high-resolution images indicate differences.",
    "Inconsistent Card Gloss: The gloss on the card back is inconsistent with known cards.",
    "Incorrect Font Style: The font style is different from genuine cards.",
    "Wrong Text Placement: The text placement is incorrect.",
    "Different Ink Quality Indicators: The ink quality appears different from genuine cards.",
    "Fake Print Lines: Visible print lines that are not present on genuine cards.",
    "Incorrect Card Back Color: The card back color is incorrect.",
    "Wrong Border Color: The border color does not match known cards.",
    "Different Design Elements: Design elements are different from genuine cards.",
    "Incorrect Text Alignment: The text alignment is incorrect.",
    "Inconsistent Card Back Design: The design does not match known genuine cards.",
    "Wrong Font Weight: The font weight is different from known cards.",
    "Poor Quality Control Indicators: Signs of poor quality control, such as uneven edges.",
    "Incorrect Gloss Finish: The gloss finish is incorrect.",
    "Different Texture Details: The texture details appear different.",
    "Fake Holo Bleed: Incorrect or missing holo bleed visible in images.",
    "Incorrect Card Thickness Indicators: Visual signs suggest incorrect thickness.",
    "Wrong Logo Size: The logo size is incorrect.",
    "Different Blue Gradient: The blue gradient is incorrect.",
    "Inconsistent Shadowing: The shadowing is inconsistent with genuine cards.",
    "Wrong Text Proportions: The text proportions are incorrect.",
    "Incorrect Color Saturation: The color saturation is off.",
    "Fake Card Template: The template does not match known genuine templates."
]
# Combine the front and back card items into a single list
card_real = [
    "Correct Font: The font used matches official Pokémon card fonts.",
    "Proper Spelling: No spelling errors on the card.",
    "Accurate Card Numbering: The card number and set symbol match the official card list.",
    "Authentic Holo Pattern: The holographic pattern is consistent with the set.",
    "Consistent Design Details: Design details match known genuine cards.",
    "Even Borders: The borders are of correct thickness and even.",
    "High Print Quality: The print is sharp and clear.",
    "Correct Material Indicators: Visual clues suggest the card is made of proper material.",
    "Authentic Texture Appearance: The texture looks like known genuine cards.",
    "Proper Gloss: The card has a glossy finish typical of authentic cards.",
    "Correct Size Indicators: Elements suggest the card is of correct size.",
    "Appropriate Weight Indicators: The card appears to have the right weight based on digital examination.",
    "Correct Thickness Indicators: Visuals suggest the card has proper thickness.",
    "Consistent Colors: Colors are accurate, neither too bright nor too dull.",
    "Properly Aligned Text: Text is well-aligned.",
    "Accurate Set Symbol: The set symbol is correct.",
    "Correct Energy Symbols: The energy symbols are accurate.",
    "Authentic Holo Foil Patterns: The holographic foil matches known patterns.",
    "Reflective Foil: The holo foil reflects light correctly.",
    "Correct Card Number: The card number matches the depicted Pokémon.",
    "Unique Card Numbers: No duplicate numbers among different cards.",
    "Correct Language: The text is in the appropriate language for an English card.",
    "Accurate Evolution Lines: Evolution lines match known Pokémon evolutions.",
    "Correct Illustrator Name: The illustrator name is accurate.",
    "Accurate Moves: The moves listed are known and correct.",
    "Correct Weakness/Resistance: The weakness and resistance symbols are accurate.",
    "Proper HP: The HP is correct for the depicted Pokémon.",
    "Valid Set Codes: Set codes match official database entries.",
    "Accurate Expansion Symbol: The expansion symbol matches the set.",
    "Genuine Card Designs: Cards depict existing Pokémon and valid designs.",
    "Correct Card Art: The card art matches official versions.",
    "Accurate Promo Symbols: Promo symbols are correct and present.",
    "Proper Artist Credits: The artist credit is accurate.",
    "Well-Cut Edges: The card edges appear smooth and even.",
    "Consistent Card Appearance: The card matches the appearance of known genuine cards.",
    "Accurate Shading: The shading on the card is correct.",
    "Valid Watermark Indicators: Watermarks match known standards.",
    "Correct Year: The year printed on the card is accurate.",
    "Authentic Edition Stamp: The edition stamp is correct and present.",
    "Accurate Evolution Requirements: Evolution requirements match known chains.",
    "Correct Rarity Symbols: The rarity symbol is accurate and present.",
    "Correct Card Type: The card type (e.g., Basic, Stage 1) is accurate.",
    "Valid Weakness: The weakness listed matches known weaknesses.",
    "Valid Resistance: The resistance listed matches known resistances.",
    "Authentic Card Abilities: The abilities listed are known and correct.",
    "Valid Trainer Cards: Trainer cards have correct effects and text.",
    "Accurate Pokémon Abilities: The Pokémon abilities are correct.",
    "Correct Attack Costs: The attack costs are accurate.",
    "Authentic Energy Cards: Energy cards have correct symbols and text.",
    "Correct Card Layout: The layout matches official Pokémon card standards.",
    "Correct Font: The font used matches official Pokémon card fonts.",
    "Proper Spelling: No spelling errors on the card back.",
    "Accurate Logo: The Pokémon logo is correctly replicated.",
    "Consistent Colors: The colors are accurate, neither too bright nor too dull.",
    "High Print Quality: The print is sharp and clear.",
    "Even Borders: The borders are of correct thickness and even.",
    "Proper Image Quality: The image is sharp and clear.",
    "Correct Blue Color: The blue color on the back is accurate.",
    "Proper Poké Ball Design: The Poké Ball design matches official cards.",
    "Accurate Color Gradient: The blue gradient is correct.",
    "Correct Pokémon Text Placement: The 'Pokémon' text placement is accurate.",
    "Proper Shadowing: The shadowing on the card is accurate.",
    "High Border Quality: The border quality is consistent and even.",
    "Consistent Gloss: The gloss on the back is consistent with genuine cards.",
    "Accurate Texture Appearance: The texture looks like known genuine cards.",
    "Correct Proportions: The proportions of elements on the back are accurate.",
    "Proper Alignment: All elements on the card back are properly aligned.",
    "Correct Gradient Transition: The transition in the gradient is smooth and accurate.",
    "Sharp Image Details: Image details are clear and sharp.",
    "Consistent Ink Quality: The ink quality matches that of genuine cards.",
    "Correct Border Color: The border color is consistent with known cards.",
    "Proper Design Layout: The design layout on the back matches genuine cards.",
    "Accurate Font Size: The font size on the back matches known standards.",
    "Consistent Color Balance: The color balance on the back is accurate.",
    "Properly Replicated Elements: All elements on the back are correctly replicated.",
    "Smooth Edges: The edges of the card back appear smooth and even.",
    "Correct Shadow Placement: Shadows are placed correctly on the back design.",
    "Authentic Design Elements: Design elements on the back are consistent with genuine cards.",
    "Accurate Text Alignment: Text on the back is well-aligned.",
    "Consistent Gloss Finish: The gloss finish on the back matches known cards.",
    "Correct Layer Indicators: Visual signs suggest correct layer structure.",
    "Proper Blue Shade: The shade of blue on the back is correct.",
    "Consistent Print Quality: The print quality on the back is consistent with genuine cards.",
    "Proper Poké Ball Placement: The Poké Ball placement is accurate.",
    "Accurate Design Details: Design details on the back are accurate.",
    "Correct Texture Indicators: The texture on the back appears correct.",
    "Smooth Color Transitions: Color transitions on the back are smooth and accurate.",
    "Authentic Element Placement: Placement of elements matches genuine cards.",
    "Properly Aligned Borders: Borders on the back are properly aligned.",
    "Accurate Image Resolution: The image resolution on the back is high and clear.",
    "Correct Ink Saturation: The ink saturation on the back is consistent with genuine cards.",
    "Proper Text Proportions: Text proportions on the back are accurate.",
    "Consistent Shadow Details: Shadow details on the back are consistent with genuine cards.",
    "Correct Gradient Colors: Gradient colors on the back are accurate.",
    "Proper Text Spacing: Text spacing on the back is correct.",
    "Consistent Print Layers: Print layers on the back match known genuine cards.",
    "Accurate Element Proportions: Proportions of elements on the back are correct.",
    "Correct Text Effects: Text effects on the back match genuine cards.",
    "Proper Alignment of Design: The overall design on the back is well-aligned.",
    "Consistent Quality Control: No visible signs of poor quality control on the back."
]

names_with_tags = [
    ("Arjun", "#12045"), ("Mei", "#34210"), ("Ibrahim", "#58734"), ("Sofia", "#78129"),
    ("Leila", "#43658"), ("Dmitry", "#98341"), ("Amina", "#21479"), ("Hiroshi", "#64387"),
    ("Fatima", "#52916"), ("Carlos", "#71543"), ("Maria", "#38014"), ("Jae", "#29167"),
    ("Ana", "#41832"), ("Liam", "#75402"), ("Emma", "#83691"), ("Yusuf", "#19235"),
    ("Priya", "#40957"), ("Wei", "#63528"), ("Aisha", "#57894"), ("Santiago", "#71420"),
    ("Elena", "#38951"), ("Hassan", "#46782"), ("Aiko", "#21593"), ("Nina", "#64372"),
    ("Pablo", "#38165"), ("Lina", "#47290"), ("Kenji", "#51943"), ("Zara", "#60238"),
    ("Omar", "#79264"), ("Rina", "#35617"), ("Nabil", "#42036"), ("Yuna", "#83156"),
    ("Kofi", "#92574"), ("Aya", "#73825"), ("Hugo", "#69231"), ("Amira", "#58392"),
    ("Luca", "#37485"), ("Iris", "#86147"), ("Aria", "#43978"), ("Ravi", "#72019"),
    ("Mira", "#53641"), ("Zane", "#48930"), ("Lina", "#26751"), ("Kiran", "#58062"),
    ("Hana", "#14938"), ("Aziz", "#62340"), ("Suri", "#78142"), ("Levi", "#29461"),
    ("Esha", "#53027"), ("Tariq", "#69184"), ("Mia", "#47382"), ("Felix", "#62491"),
    ("Iman", "#82134"), ("Ryo", "#65231"), ("Hana", "#41856"), ("Amir", "#29147"),
    ("Isla", "#73920"), ("Noor", "#54618"), ("Elias", "#83942"), ("Lila", "#61358"),
    ("Hugo", "#28461"), ("Mira", "#52019"), ("Arun", "#36154"), ("Ava", "#74829"),
    ("Rami", "#41572"), ("Suki", "#59841"), ("Leif", "#23617"), ("Ines", "#94201"),
    ("Nia", "#47351"), ("Hiro", "#68124"), ("Leila", "#32941"), ("Zane", "#58073"),
    ("Maya", "#46829"), ("Omar", "#15427"), ("Kira", "#29016"), ("Ryu", "#51483"),
    ("Lina", "#73145"), ("Amir", "#64028"), ("Zara", "#38917"), ("Leo", "#79204"),
    ("Hana", "#54123"), ("Niko", "#81736"), ("Fara", "#26918"), ("Ali", "#43872"),
    ("Rina", "#63148"), ("Ayan", "#74931"), ("Isha", "#52186"), ("Aria", "#39284"),
    ("Luca", "#48691"), ("Mila", "#17924"), ("Noor", "#63127"), ("Zaid", "#75834"),
    ("Sia", "#42195"), ("Teo", "#31968"), ("Hana", "#56281"), ("Rami", "#84016"),
    ("Lina", "#39482"), ("Amir", "#52109"), ("Yara", "#68319"), ("Felix", "#27941"),
    ("Suri", "#74092"), ("Liam", "#48176"), ("Zara", "#65283"), ("Niko", "#31475"),
    ("Ava", "#56128"), ("Leo", "#83914"), ("Lina", "#29673"), ("Mira", "#74281"),
    ("Omar", "#61432"), ("Rina", "#38961"), ("Aya", "#57049"), ("Elias", "#21968"),
    ("Aria", "#68231"), ("Hugo", "#54719"), ("Hana", "#13842"), ("Kenji", "#49206"),
    ("Yuna", "#57138"), ("Kofi", "#63194"), ("Iris", "#48217"), ("Nabil", "#19463"),
    ("Ryo", "#36281"), ("Amina", "#71029"), ("Zane", "#52843"), ("Mira", "#64917"),
    ("Luca", "#38152"), ("Aiko", "#21975"), ("Zara", "#76481"), ("Carlos", "#58192"),
    ("Ana", "#42187"), ("Jae", "#71954"), ("Elena", "#63014"), ("Liam", "#29347"),
    ("Emma", "#54689"), ("Yusuf", "#78143"), ("Priya", "#61495"), ("Wei", "#35287"),
    ("Aisha", "#49061"), ("Santiago", "#21874"), ("Hiroshi", "#75982"), ("Nina", "#13659"),
    ("Fatima", "#68421"), ("Dmitry", "#43058"), ("Amina", "#51249"), ("Hiroshi", "#67318"),
    ("Rina", "#28416"), ("Omar", "#75329"), ("Mei", "#46138"), ("Ibrahim", "#92751"),
    ("Lina", "#63418"), ("Kenji", "#47316"), ("Kofi", "#38174"), ("Aiko", "#51298"),
    ("Suri", "#71983"), ("Zara", "#64531"), ("Sia", "#35274"), ("Amir", "#49817"),
    ("Rami", "#25139"), ("Nabil", "#62497"), ("Zane", "#18935"), ("Wei", "#57362"),
    ("Priya", "#49027"), ("Yuna", "#67231"), ("Leila", "#83916"), ("Mei", "#19368"),
    ("Yusuf", "#62197"), ("Jae", "#45712"), ("Emma", "#39425"), ("Liam", "#76832"),
    ("Elena", "#52093"), ("Ana", "#31684"), ("Carlos", "#48276"), ("Luca", "#69143"),
    ("Mira", "#24358"), ("Zane", "#51927"), ("Aiko", "#37841"), ("Nina", "#59016"),
    ("Santiago", "#83174"), ("Wei", "#24631"), ("Aisha", "#57314"), ("Priya", "#42985"),
    ("Yusuf", "#68493"), ("Leila", "#73156"), ("Mei", "#42871"), ("Ibrahim", "#51429"),
    ("Lina", "#27483"), ("Kenji", "#63195"), ("Kofi", "#48716"), ("Aiko", "#72053"),
    ("Suri", "#59314"), ("Zara", "#81436"), ("Sia", "#51297"), ("Amir", "#47938"),
    ("Rami", "#62074"), ("Nabil", "#13846"), ("Zane", "#74295"), ("Wei", "#31958"),
    ("Priya", "#58312"), ("Yuna", "#49275"), ("Leila", "#68391"), ("Mei", "#72945")
]
authenticator = [card_issues ,card_real,names_with_tags ]

def auth_comment(authenticator=authenticator,preds=None,choice = None):
    if choice == "Japanese Modern" or choice == "Japanese Vintage":

      if preds == [1]:
          sentence = random.sample(authenticator[0],2)
      else:
          sentence = random.sample(authenticator[1],2)
    else:

      if preds == [0]:
          sentence = random.sample(authenticator[0],2)
      else:
          sentence = random.sample(authenticator[1],2)
    names = random.sample(authenticator[2],2)
    return sentence, names
